### ISSUE TITLE
Links in navbar

### ISSUE THREAD

**Issue by tkoberom** [max-schlosser/DigitaleMedien#1]
Ich habe in der navbar 2 varianten für die Darstellung eines Links untergebracht. Welche würde euch zusagen?

**Comment by max-schlosser** [comment]
Ich würde einen Button mit Hover-Effekt bevorzugen. http://ianlunn.github.io/Hover/

**Comment by StephanWagener** [comment]
Dem stimme ich zu aber das können max und ich ja dann machen über den sytle
________________________________
Von: Max Schlosser [notifications@github.com]
Gesendet: Dienstag, 13. Oktober 2015 19:56
An: max-schlosser/DigitaleMedien
Betreff: Re: [DigitaleMedien] Links in navbar (#1)


Ich würde einen Button mit Hover-Effekt bevorzugen. http://ianlunn.github.io/Hover/

**Comment by StephanWagener** [comment]
desweiteren würde ich nen button in die website einbauen der den style dynamisch ändert
________________________________
Von: Wagener, Stephan
Gesendet: Mittwoch, 14. Oktober 2015 11:17
An: max-schlosser/DigitaleMedien; max-schlosser/DigitaleMedien
Betreff: AW: [DigitaleMedien] Links in navbar (#1)

Dem stimme ich zu aber das können max und ich ja dann machen über den sytle
________________________________
Von: Max Schlosser [notifications@github.com]
Gesendet: Dienstag, 13. Oktober 2015 19:56
An: max-schlosser/DigitaleMedien
Betreff: Re: [DigitaleMedien] Links in navbar (#1)


Ich würde einen Button mit Hover-Effekt bevorzugen. http://ianlunn.github.io/Hover/

**Comment by tkoberom** [comment]
Sorry... ich wollte den issue euch beiden zuordnen.

**Comment by max-schlosser** [comment]
Man kann meines Wissens nach leider nur einer Person einen Issue zuordnen. Aber ist schon richtig gut, dass du einen gemacht hast!

**Comment by StephanWagener** [comment]
die links waren aber nur zu anderen websites wir brauchen aber welche die auch interne überschriften verweisen

**Comment by max-schlosser** [comment]
Was bedeutet, dass wir Unterseiten anlegen und darauf verlinken müssen. Das könnte zu einem Problem führen bzgl. der Linkangaben im HTML. Haben wir von der Hochschule einen Webserver zur Verfügung gestellt bekommen? Professor Hartmann wollte sich darum kümmern, oder?

**Comment by StephanWagener** [comment]
freiwillige hierfür?

**Comment by max-schlosser** [comment]
Erstmal sollten wir uns die genaue Vorgehensweise überlegen, bevor du jemandem eine Aufgabe zuweisen möchtest.

**Comment by tkoberom** [comment]
Der issue kann ja noch nicht geschlossen werden...aber betrifft ja auch nicht Aufgabe 3..!!!! also reopened aber noch unrelevant

**Comment by StephanWagener** [comment]
die links passen jetzt aber eigentlich
