### ISSUE TITLE
Header genauso breit wie Navigationsbar und Content zusammen

### ISSUE THREAD

**Issue by max-schlosser** [max-schlosser/DigitaleMedien#10]
Der Header soll so breit sein wie Navigationsbar und Content zusammen breit sind, sodass es einheitlich aussieht.

**Comment by tkoberom** [comment]
Nächste Woche ist responisive design als Thema in der Vorlesung dran...also würde ich lieber noch abwarten bis alle mehr darüber wissen

**Comment by StephanWagener** [comment]
das ist aber nicht ganz das richtige thema dafür nur teilweise. hollas simmmmi und ich besprechen das morgen nochmal

**Comment by StephanWagener** [comment]
guckt mal ob ihr das bei euch hin bekommt ich versuche bei uns ein anderes design zu fahren da brauche ich das dann nicht mehr.

**Comment by frozenyogurt** [comment]
Done oder?

**Comment by max-schlosser** [comment]
In meinen Augen auch erledigt.

@all Man kann übrigens auch mit einem Commit gleich einen Issue schließen.
