### ISSUE TITLE
Platzmanagement

### ISSUE THREAD

**Issue by max-schlosser** [max-schlosser/DigitaleMedien#11]
Rechts und links der Webseite sind zu große leere Flächen auf einem Widescreen Display. Wir sollten die Webseite nach Möglichkeit so dynamisch schreiben wie möglich und auf feste Werte verzichten.

**Comment by StephanWagener** [comment]
wir arbeiten momentan oft mit prozenten also es ist schon sehr dynamisch. bei uns habe ich die werte etwas angepasst.

**Comment by tkoberom** [comment]
#10 ...erledige ich zusammen mit dieser issue...der bodycontent hat 80% und einen abstand zum rand um jeweils 10% ..oder hättet ihr einen anderen vorschlag

**Comment by StephanWagener** [comment]
ja das sollte passen nur auch auf die gleichen breiten gucken

**Comment by frozenyogurt** [comment]
#10  closed, und der damit auch denke ich.
