### ISSUE TITLE
Inhalt

### ISSUE THREAD

**Issue by max-schlosser** [max-schlosser/DigitaleMedien#12]
Wir haben die Aufgabe uns aus der Sicht von Isaac Newton vorzustellen. Hierfür soll jeder einen Teil des Inhaltes erarbeiten. Jeder der einen bestimmen Teil erarbeiten möchte, kann sich hier eintragen. Wir arbeiten hier sozusagen nach FIFO. :smile:

**Comment by max-schlosser** [comment]
Dazu kommt, dass wir interne/externe Links, Bilder, Tabellen und Listen verwenden sollen. Also bittet achtet darauf vielfältig den Inhalt darzustellen.

Für den internen Link haben wir uns eine Startseite gedacht, welche nur eine kurze Zusammenfassung über unsere Person bereithält. Auf dieser Startseite soll dann ein interner Link auf unsere Webseite verweisen, welche wir momentan entwickeln.

**Comment by StephanWagener** [comment]
dann mal los @fhollas

**Comment by fhollas** [comment]
Bin dran. Morgen Abend spätestens ist der Inhalt fertig.

**Comment by StephanWagener** [comment]
Gut. Inwiefern hast du schon Bilder, Tabellen und sowas drin?

**Comment by StephanWagener** [comment]
Passt soweit erstmal.
