### ISSUE TITLE
Header verbessern

### ISSUE THREAD

**Issue by max-schlosser** [max-schlosser/DigitaleMedien#13]
Lasst uns Ideen für den Header sammeln. Momentan sieht dieser überhaupt nicht ansprechend aus. Das müssen wir ändern.

**Comment by tkoberom** [comment]
Ich finde, dass das Portait rechts platziert werden sollte und noch ein ansprechendes Backgroundmuster gesucht werden müsste...

**Comment by StephanWagener** [comment]
das können wir im anderen style ja so umsetzen

**Comment by StephanWagener** [comment]
ich würde sagen, das wir im header links und rechts neben navbar und überschrift die bilder machen. Nicht wie momentan untereinander.

**Comment by max-schlosser** [comment]
Von welchem Style sprichst du? Ich kann in beiden Styles nicht mehrere Bilder im Header ausfindig machen.

**Comment by StephanWagener** [comment]
Ja aber im Style 2 kann man die ja unterbringen neben der Überschrift.

**Comment by frozenyogurt** [comment]
"Ich kann in beiden Styles nicht mehrere Bilder im Header ausfindig machen."
"Ja aber im Style 2 kann man **die** ja unterbringen neben der Überschrift."
Ihr redet aneinander vorbei und ich verstehe auch nicht was Stephan meint.

**Comment by max-schlosser** [comment]
👍

**Comment by StephanWagener** [comment]
Na das man einfach rechts und links beispielsweise neben der Überschrift ein paar Bilder positioniert.

**Comment by frozenyogurt** [comment]
Ist das nicht das gleiche wie #14  ?

**Comment by StephanWagener** [comment]
Ja so ähnlich einfach den Header anschaulicher machen.

**Comment by StephanWagener** [comment]
Sollte im Style 2 noch ein wenig ausgeschmückt werden.
