### ISSUE TITLE
Titelbild für die Website

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#14]
Am besten irgendein großes bild als eine Art header oder mit dem jetzigen kombiniert.

**Comment by tkoberom** [comment]
Für style.css1 wurde das schon umgesetzt, wenn dies noch für 2 gemacht werden könnte, kann dieser issue ja geschlossen werden.

**Comment by StephanWagener** [comment]
genau das nehme ich heute mal in angriff

**Comment by StephanWagener** [comment]
Ich bin der Meinung, dass wir jetzt im 2. Style kein Titelbild brauchen. Kurze Abstimmung!? Dann kann der auch geschlossen werden.

**Comment by max-schlosser** [comment]
Meiner Meinung nach kann der Style so bleiben.

**Comment by frozenyogurt** [comment]
Was ist mit Titelbild gemeint? Bild als Hintergrund im Header, Bild als Hintergrund des Bodys? Oder dieses Bild von Newton im Header?
Wenn ihr in den Style2 nicht mehr viel Arbeit stecken wollt, dann kann er von mir aus auch gern so bleiben, sonst würde ich wenn es keiner macht noch daran arbeiten.
Aber halbe Sachen mache ich nicht :O..

**Comment by StephanWagener** [comment]
Da kannst du dich erstmal austoben und ich nehme mich des Responsive Design und der Cookies an.

**Comment by StephanWagener** [comment]
Damit war eigentlich das Headerbild gemeint.

**Comment by StephanWagener** [comment]
Sollte im Style 2

**Comment by StephanWagener** [comment]
Issue 13 reicht.
