### ISSUE TITLE
Sidebar actions einbinden

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#16]
Bei Clicks in der Sidebar sollte die seite den entsprechenden Inhalt anzeigen. Umgekehrt genauso, aber das wird eher schwierig denke ich.

**Comment by StephanWagener** [comment]
hier funktioniert es halbwegs in eine richtung

**Comment by tkoberom** [comment]
Das funktioniert doch dann mittels PHP oder irre ich mich da @StephanWagener ?

**Comment by StephanWagener** [comment]
ich denke eher über Javaskript, jquery oder ajax

**Comment by StephanWagener** [comment]
ich denke das passt soweit erstmal mit den actions der sidebar
