### ISSUE TITLE
footer inhalt und design bearbeiten

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#17]
der Inhalt ist natürlich nur schrott und vom design könnte man sich am header orientieren als eine art rahmen.

**Comment by tkoberom** [comment]
Design passt ...inhalt siehe #12

**Comment by StephanWagener** [comment]
naja als kontakt schlosser der russe ist vielleicht nicht so klever

**Comment by StephanWagener** [comment]
kümmer dich mal bitte um einen sinnvollen Ihalt

**Comment by StephanWagener** [comment]
guck dir mal an was in einem richtigen footer alles drin steht. da fehlen noch datenschutz rechte etc

**Comment by max-schlosser** [comment]
Sinnlos! Das brauchen wir überhaupt nicht in unserem kleinen Projekt, welches niemals im Internet öffentlich erreichbar sein wird. Du darfst dir den Issue gerne selber zuweisen, wenn du Bock darauf hast. Ich würde meine Zeit lieber in sinnvolle Aufgaben investieren.

Die Angaben, welche für uns sinnvoll sind stehen drin. Und was das Design angeht, darüber können wir gerne nocheinmal einen Issue eröffnen.
