### ISSUE TITLE
Einfügen von Beispiel-Layouts

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#18]
einfach mal nen paar Listen, tabellen oder bilder im content erzeugen, damit die bearbeitung am ende mit dem Inhalt schnell geht.

**Comment by tkoberom** [comment]
für listen kann man sich z.Bsp. an der navbar inspirieren lassen

**Comment by StephanWagener** [comment]
ja aber die ist ja in dem Sinne keine richtige Liste

**Comment by StephanWagener** [comment]
habe ich bei den quellen mal gemacht auch zu recherche zwecken.

**Comment by StephanWagener** [comment]
Das passt soweit auch mit den verschiedenen Layouts. Wenn noch welche aus der Aufgabe fehlen, dann macht dafür nen neuen Issue auf.
