### ISSUE TITLE
Gestaltung des Footers

### ISSUE THREAD

**Issue by tkoberom** [max-schlosser/DigitaleMedien#2]
Habt ihr schon eine Idee wie der footer gestaltet bzw. wie er genau positioniert werden soll?

**Comment by StephanWagener** [comment]
nutz einfach die footerklasse und überlege dir ein geeignetes Impressum

**Comment by tkoberom** [comment]
Wie breit soll diese sein? navbar + content ? oder größer ?
Durchsichtig oder ähnlich der anderen klassen?

**Comment by StephanWagener** [comment]
navbar + content und so wie die anderen

**Comment by max-schlosser** [comment]
Gestaltung des Footers wurde auch gelöst. Damit wird der Issue geschlossen.
