### ISSUE TITLE
Responsive Webdesign

### ISSUE THREAD

**Issue by tkoberom** [max-schlosser/DigitaleMedien#20]
Hier ein guter Link zum Thema Responisve Webdesign :sparkles: 

Wer Bock hat kann sich ja schonmal damit beschäftigen

http://www.webmasterpro.de/coding/article/css-responsive-webdesign-media-queries-fuer-iphone-ipad-und-smartphones.html

**Comment by tkoberom** [comment]
auch sehr gut beschrieben ...die 0,5 h lohnen sich , da man etwas über html5 , css3 und resp. design erfährt :mag: 
https://www.youtube.com/watch?v=g2taIe7ZFUA

**Comment by StephanWagener** [comment]
ein wenig davon habe ich beim neuen Update des Projektes verwendet.

**Comment by fhollas** [comment]
Nochmal als Erinnerung, dass wir hier zwischen drei verschiedenen Gerätetypen (Handy, Tablet, PC) unterscheiden können sollen.

**Comment by StephanWagener** [comment]
Ja das muss noch erledigt werden

**Comment by StephanWagener** [comment]
Hier ergeben sich noch einige Probleme, die jeder sehen sollte, wenn er das Fenster verkleinert. Um einige Unschönheiten würde ich mich kümmern. Noch jemand der helfen will ?

**Comment by max-schlosser** [comment]
Ich kann aber heute Abend nach dem TT unterstützen.

**Comment by frozenyogurt** [comment]
Ich gucke mal, was ich heute dazu finden kann und ob es eine "einfache" Lösung gibt.

**Comment by StephanWagener** [comment]
Einfach gucken, was sieht schlecht aus wenn man die Fenstergröße verkleinert.

**Comment by frozenyogurt** [comment]
@StephanWagener 
Hab euch ja die Bilder von meinem Handy geschickt, dort ist eigentlich alles in Style 1 okay.
Der Header ist dort zwar klein, aber gehen tut es.

**Comment by StephanWagener** [comment]
Das Responsive Design fehlt nur noch für die Startseite im 2. Style. Vielleicht noch kleine Verbessrungen bei der Navigtaion, aber sonst passt das.
