### ISSUE TITLE
Pixelwerte in em-Werte umschreiben

### ISSUE THREAD

**Issue by tkoberom** [max-schlosser/DigitaleMedien#21]
http://pxtoem.com/
Hiermit könnt ihr die Werte umrechnen.
Für Responsive Design dürfen wir nur em und % Werte verwenden.

**Comment by StephanWagener** [comment]
ist im style 2 erledigt

**Comment by tkoberom** [comment]
wer nimmt das für style1 vor ?

**Comment by StephanWagener** [comment]
einfach jemanden vom ersten team zuweisen @fhollas
