### ISSUE TITLE
navigationbar

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#23]
navigationbar für einige themen wäre vielleicht ganz gut also die oben wie tabs stehen

**Comment by StephanWagener** [comment]
hier waren die vorschläge dass man in die navbar ein quiz und noch einen punkt machen könnte

**Comment by StephanWagener** [comment]
ein weiterer punkt wäre eine kurze vorstellung des teams

**Comment by StephanWagener** [comment]
oder andere wichtige physiker

**Comment by tkoberom** [comment]
wird zu voll...könnte aber woanders hin ...in einen neuen container

**Comment by StephanWagener** [comment]
so wie es simmi hat passt das denke ich nur der punkt mit dem leben passt nicht ganz weil der sich zu stark mit dem inhalt der home seite überschneidet

**Comment by max-schlosser** [comment]
Wie ist der Stand dieses Isseues? Kann er geschlossen werden?

@StephanWagener Bitte verwende Satzzeichen. Deinen Kommentare sind sonst wirklich sehr schwer zu verstehen.

**Comment by StephanWagener** [comment]
Ja der kann geschlossen werden. Bei Fehlern oder Styleänderungen kann man ja einen  neuen angepassten Issue aufmachen.
