### ISSUE TITLE
{!}   -  -   -    ○====8 

### ISSUE THREAD

**Issue by tkoberom** [max-schlosser/DigitaleMedien#24]
Ich hab dazu mal nen issue erstellt. Mach die Webseite fertig!!!!!!!!!

Wir haben schon issues geschlossen da hast du noch in die Windeln geschissen 👈👽👉 💘💞💕💖💗

**Comment by fhollas** [comment]
Solche issues können nur wahre Führer schließen.

**Comment by tkoberom** [comment]
Mittwochabend war ein voller Erfolg :tada: :v: :ghost:  , deswegen kann dieser Issue nun geschlossen werden!
