### ISSUE TITLE
bugs von style 1

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#25]
bugs in dem ersten und dem zweiten style sollten behoben werden. vor allem im bezug auf bezug auf die effekte mit dem media screen und der sidebar. ich hab da einfach mal hollas zugewiesen weil viel im ersten layout zu machen ist.

**Comment by StephanWagener** [comment]
übernehmt bitte einige sachen aus dem 2. style und dann behebt die fehler beim anzeigen.

**Comment by StephanWagener** [comment]
Der kann auch zu, weil jetzt eher Style 2 angepasst werden muss.

**Comment by frozenyogurt** [comment]
:DD .. Richtig gut wie du dich hier mit dir selbst unterhälst ;-)
