### ISSUE TITLE
up button

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#26]
wenn der euch so gefällt dann schließt den issue hier!?

**Comment by tkoberom** [comment]
könnte ansprechender sein...simi such du mal bitte einen raus @frozenyogurt

**Comment by StephanWagener** [comment]
ja das image habe ich kurz zusammen geschustert

**Comment by frozenyogurt** [comment]
Auf der aktuellen Version ist kein Pfeil mehr vorhanden. Wenn noch gewollt, würde ich den hier nehmen und unten um 180° drehen sowie einen Hover effect einbinden, dass er bei Mouseover aufleuchtet: http://fortawesome.github.io/Font-Awesome/icon/arrow-circle-down/
Wenn ihr die Funktion nicht mehr wollt, schließt die Question.

**Comment by StephanWagener** [comment]
ja der sollte passen

**Comment by max-schlosser** [comment]
Wo kommt dieser Button zum Einsatz? Ich konnte die Stelle leider nicht finden.

**Comment by StephanWagener** [comment]
ich versuche den an der rechten seite zu positionieren wenn man eine bestimmte position erreicht hat

**Comment by max-schlosser** [comment]
Welche Funktion soll er dann bekommen?

@StephanWagener Satzzeichen :laughing:

**Comment by StephanWagener** [comment]
Der soll nur wieder nach ganz oben scollen, wenn der Ihnalt zu lang ist, mehr eigentlich nicht.

**Comment by StephanWagener** [comment]
den bau ich jetzt mal mit simmis image ein

**Comment by StephanWagener** [comment]
passt der jetzt? @frozenyogurt @tkoberom @Us3r12345 @fhollas

**Comment by max-schlosser** [comment]
Es funktioniert. Das Bild (der kleine Pfeil) wird bei mir aber nicht angezeigt.

**Comment by StephanWagener** [comment]
Wie kann es funktionieren, wenn du den Button nicht siehst?

**Comment by max-schlosser** [comment]
Jetzt sehe ich das Bild für den Button. Vorher war dort einfach ein Symbol was zeigte, dass die Datei defekt wäre.

**Comment by StephanWagener** [comment]
also ich denke das passt jetzt
