### ISSUE TITLE
fallender apfel

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#27]
Vielleicht könnte man am Rand oder irgendwo anders noch den fallenden Apfel darstellen bzw. animieren.

**Comment by tkoberom** [comment]
coole idee aber wie willst du das animieren ?

**Comment by StephanWagener** [comment]
na der folgt beim scrollen auf irendeine art und weise oder ganz anders da b in ich noch offen für alle vorschläge

**Comment by frozenyogurt** [comment]
Meine Idee:
http://www.gifmania.co.uk/Space-Animated-Gifs/Animated-Astronomy/Astronomers/Isaac-Newton/Newton-And-Apple-Tree-90808.gif
Einbinden und bei Klick solls abspielen.

**Comment by StephanWagener** [comment]
auch gut die frage ist nur ob das so reicht ich hätte mir das über die komplette seite vorgestellt aber das ist bestimmt zu schwierig oder?

**Comment by max-schlosser** [comment]
Ich finde Stephans Idee auch richtig gut. Und ich finde, dass man sich das richtig gut vorstellen kann. Leider weiß ich auch nicht, wie man das umsetzen kann. Aber wenn ich Zeit habe, frage ich mal auf Arbeit nach.

**Comment by StephanWagener** [comment]
wäre cool das so umzusetzen in einem style wenigstens

**Comment by max-schlosser** [comment]
+1

**Comment by tkoberom** [comment]
http://www.w3schools.com/css/css3_animations.asp
das würde sicher auch funken und aktuell, da die so nur in css3 möglich ist

**Comment by max-schlosser** [comment]
Wie ich finde ein gutes <a href="http://fairphone.com/">Beispiel</a>. Scrollt einfach mal ein wenig nach unten.

**Comment by tkoberom** [comment]
Das wurde auch mit der Variante gemacht ..die ich zuvor gepostet habe...also würde ich mich mal daran versuchen

**Comment by StephanWagener** [comment]
mach das

**Comment by StephanWagener** [comment]
Dafür reicht die Zeit nicht mehr.
