### ISSUE TITLE
social media

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#28]
Ein paar social media funktionen könnte man auch implementieren, selbst wenn es nur eine demo ist.

**Comment by tkoberom** [comment]
an was denkat du da genau? habt ihr vorschläge dazu ?

**Comment by StephanWagener** [comment]
einfach neben den menu button hauen zum beispiel, aber erstmal nur als demo

**Comment by max-schlosser** [comment]
Wurde scheinbar mit "#NewtonIsAwesome" erledigt oder? Oder habt ihr vor APIs von großen Netzwerken einzubinden?

**Comment by StephanWagener** [comment]
facebook fehlt noch aber dann kann das ding geschlossen werden

**Comment by max-schlosser** [comment]
Dann weise ich dir den Issue zu. Aber meiner Meinung nach ist das überflüssig.

**Comment by frozenyogurt** [comment]
Facebook hab ich doch schon reingemacht. Siehe http://dimeproject.111mb.de/root/HtmlCode/index.html
. Closed
