### ISSUE TITLE
article und sidebar

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#29]
die positionen und der abstand zwischen den beiden passt noch nicht ganz

**Comment by tkoberom** [comment]
welchen style meinst du Kollege

**Comment by StephanWagener** [comment]
style 2 aber das sollte jetzt nicht mehr ganz so schlimm sein

**Comment by tkoberom** [comment]
wenn das jqueryfile sich auf die sidebar bezieht , wird ja quasi nur der margin des aside-containers verändert ...oder versteh ich da was falsch?

**Comment by StephanWagener** [comment]
eigentlich verändere ich aside und srcticle mittels der IDs so, dass man den Unterschied beim scrollen nicht bemerkt, aber durch die Veränderungen muss das wieder angepasst werden.

**Comment by tkoberom** [comment]
versuch mal nicht das margin zu verwenden sondern gib dem article per position: relative und left und top...einen bestimmten platz...
der margin macht so nur probleme

**Comment by StephanWagener** [comment]
ja ich weiß aber anders geht das irgendwie nicht weil ich die position auf fixed setze und die sich nicht mit display inline block und so verträgt

**Comment by StephanWagener** [comment]
passt eigentlich, wenn noch was geändert werden muss geht das schnell
