### ISSUE TITLE
2 Style Sheets

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#3]
Ich würde mich um einen Schalter kümmern, der die beiden unterschiedlichen Styles wechselt.

**Comment by tkoberom** [comment]
Möchtest du das mittels JS lösen ? 
Wäre gut wenn der unauffällig oben links oder rechts wäre.

**Comment by StephanWagener** [comment]
lade dir mal die aktuellste version da habe ich schon einiges eingefügt aber der Style an sich gefällt mir noch nicht

**Comment by max-schlosser** [comment]
Konntest du das Problem schon lösen?

**Comment by StephanWagener** [comment]
ich nicht nein aber ich arbeite erstmal am hover effekt und so

**Comment by max-schlosser** [comment]
Stephan scheint den Umschalter bereits eingebaut zu haben. Deswegen schließe ich diesen Issue.
