### ISSUE TITLE
sidebar wechsel zu media screen

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#30]
wenn man runter scrollt und dann in den media screen wechselt bleibt die sidebar an der seite.

**Comment by frozenyogurt** [comment]
Was ist der Media Screen? Und soll die Sidebar da nicht bleiben? Oder meinst du die scrollt nicht mit?
Erklärung bitte oder ist das schon gefixt? Dann bitte Close.

**Comment by StephanWagener** [comment]
Irgendwie schiebt sich die Sidebar nicht über den article, wenn man im scrollen die Größe des Fensters ändert.

**Comment by frozenyogurt** [comment]
Achso, du willst, dass bei kleineren Displays die Sidebar über den article rutscht?
Finde die Funtion der Sidebar dann aber sinnlos.
Von mir aus kann das so bleiben.

**Comment by StephanWagener** [comment]
Das ist ja eigentlich schon der Fall, aber nicht, wenn man die Sidebar Position fixed ist, wegen des Scrollens.

**Comment by StephanWagener** [comment]
Testet das mal bitte nochmal. Wenn ihr das Browser Fenster resized (erstmal kein Zoom) Dann sollte keine Überlagerung der Sidebar mit dem Article erfolgen. Das resizen macht ihr einmal, wenn die Sidebar mitscrollt und einmal, wenn ihr ganz oben auf der Seite seid. @tkoberom @frozenyogurt
