### ISSUE TITLE
Bild auf der Welcome Seite 

### ISSUE THREAD

**Issue by frozenyogurt** [max-schlosser/DigitaleMedien#31]
Ich habe mir gerade die neueste Version der Welcome Seite auf dem Handy angeguckt (http://dimeproject.111mb.de/root/HtmlCode/index.html).
Dort ist das Bild nur klein im oberen Teil des Bildschirms dargestellt.
Wäre es möglich, dass das Bild immer von oben links bis nach unten rechts geht, ohne, dass es dabei gestreckt wirds sondern man je nach Bildschirm immer nur einen Ausschnitt wählt?

**Comment by StephanWagener** [comment]
sicherlich gibt es da möglichkeiten ich guck  ich da mal um

**Comment by frozenyogurt** [comment]
Obwohl "background-size: cover;" eingestellt ist, geht das nicht. Siehe Screenshot. Ich gucke da heute mal was es für einen möglichen Fix gibt.
![test](https://cloud.githubusercontent.com/assets/11294516/11207365/170fc030-8d15-11e5-8d05-7940817d4a02.png)

**Comment by frozenyogurt** [comment]
Schon done.

html {
  height: 100%
}

Hat's gefixt.
