### ISSUE TITLE
Umlaute in der quiz.html

### ISSUE THREAD

**Issue by frozenyogurt** [max-schlosser/DigitaleMedien#32]
Umlaute werden im Quiz nicht richtig angezeigt, obwohl ich den Header mit den Metas nur übernommen und nichts geändert habe.

**Comment by StephanWagener** [comment]
vielleicht hat das keine auswirkungen auf die php dateien

**Comment by frozenyogurt** [comment]
Ist ja jetzt eine HTML. Hab kein PHP benötigt.

**Comment by StephanWagener** [comment]
achso okay dann liegt es wahrscheinlich daran, dass du die seiten vervielfältigst

**Comment by StephanWagener** [comment]
scheinen jetzt behoben zu sein
