### ISSUE TITLE
Aufbau bzw Struktur der Seite

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#33]
mir ist aufgefallen das wir noch sehr redundant arbeiten was den aufbau des layouts angeht. ich werde versuchen den inhalt der verschiedenen tabs in einzelne container zu packen und dann über ajax nur die zu ändernden inhalte neu zu laden.

**Comment by tkoberom** [comment]
So soll es ja auch sein ...man könnte die Inhalte ja schonmal so umbauen dass da nur der article-part drin steht..wer hat die seiten dupliziert? der kann das ja auch gleich vornhemen

**Comment by StephanWagener** [comment]
nein das mach ich das muss sowieso kompatibel mit ajax sein am ende das geht schon

**Comment by tkoberom** [comment]
ich finde der content sollte ein wenig zentriert werden bei style1 ...so wies jetzt is finde ich das nicht ansehlich und die navbar sollte auch lieber an den header ausgerichtet werden und nicht an den content oder nich ?

**Comment by StephanWagener** [comment]
mach ruhig deine veränderungen und wenn wir die nicht gelungen finden bauen wir die wieder aus

**Comment by tkoberom** [comment]
das habe ich jetzt schon zweimal gemacht...absprechen und bei einem design belassen wäre vllt nicht schlecht

**Comment by StephanWagener** [comment]
ja das jetztige passt ja nicht ganz also leg mal eins schlichtes hin wie abgesprochen und dann wird angepasst

**Comment by StephanWagener** [comment]
dieser Issue bezieht sich eher auf den Aufbau der Website nicht auf den Style. Ich stehe hierzu mit Herr Hartmann in Kontakt, um eine Lösung zu finden, weil Hans und Sven mich auch schon gefragt haben, wie man das am besten löst.

**Comment by max-schlosser** [comment]
@StephanWagener, du sagtest gerade eben am Telefon, dass sich dieser Issue auch darauf bezieht, dass man die Navigationsbuttons des Browsers nicht verwenden kann.

Vielleicht kannst du den Inhalt dieses Issues ausführlich und für alle verständlich niederschreiben, damit es zu keinen Missverständnissen kommt.

**Comment by StephanWagener** [comment]
diesen issue mache ich es geht schlicht weg um das handlen der klicks auf die navbar und wie ich den content dann darstelle also wie ich ihn ohne die ganze seite neu zu laden einfügen kann

**Comment by max-schlosser** [comment]
@StephanWagener Ich kann es nicht oft genug schreiben. Verwende doch mal bitte Satzzeichen damit deine Kommentare leichter verständlich werden.

**Comment by StephanWagener** [comment]
Diesen Issue mache ich. Es geht schlicht weg, um das handlen der klicks auf die navbar und wie ich den content dann darstelle. Also wie ich ihn ohne die ganze seite neu zu laden, einfügen kann.

**Comment by StephanWagener** [comment]
okay belassen wir es vorerst bei der jetzigen Variante
