### ISSUE TITLE
Vortrag für den 16.11.

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#34]
einer sollte den mal vorbereiten mit aufbau des DOM und so, aber ein wenig musst du noch warten bis die Struktur wieder stimmt.

**Comment by max-schlosser** [comment]
Gibt es noch mehr Informationen dazu?
@StephanWagener gib mir ein Zeichen, wenn die Struktur fertig ist.

**Comment by StephanWagener** [comment]
ja wenn ich das mit hartmann geklärt habe kannst du anfangen ich sag bescheid

**Comment by max-schlosser** [comment]
@StephanWagener Verwende Satzzeichen!

**Comment by StephanWagener** [comment]
Wenn du mit dem Vortrag fertig bist, dann schließe den Issue bitte. @max-schlosser
