### ISSUE TITLE
result beim quiz

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#35]
die result ansicht muss noch überholt werden, aber der rest passt soweit denke ich.

**Comment by StephanWagener** [comment]
du kannst den wieder mir zuweisen wenn du denkst das ist zu hart.

**Comment by frozenyogurt** [comment]
Wenn du nur den Style meinst probiere ich es natürlich. Die Auswertung passt aber ja.

**Comment by StephanWagener** [comment]
genau nur der style

**Comment by StephanWagener** [comment]
arbeite ruhig mit "p" oder anderen elementen die du mit display ein und ausblendest je nachdem welcher inhalt angezeigt wird

**Comment by StephanWagener** [comment]
du kannst auch den vorhandenen button style verwenden

**Comment by max-schlosser** [comment]
Bei mir passt die Auswertung nicht. Ich komme nur auf maximal 80%. Die letzte Frage wird bei mir nicht ausgewertet! (FF 42.0)

**Comment by frozenyogurt** [comment]
Behoben. Style wurde auch angepasst. Wenns noch weitere Änderungen vorgenommen werden sollen bitte neuen Thread, da das meiner Meinung nach schon ganz gut aussieht.
--> Closed.
