### ISSUE TITLE
StyleChanger Button beim Quiz

### ISSUE THREAD

**Issue by frozenyogurt** [max-schlosser/DigitaleMedien#36]
Der ist nur im Quiz rechts ein bisschen kleiner.
Kann das einer von denen bitte fixen, die den gemacht haben?
Danke :)
@tkoberom 
@StephanWagener

**Comment by StephanWagener** [comment]
ja das habe ich auch schon gesehen und das müsste im zusammenhang mit der load funktion stehen

**Comment by StephanWagener** [comment]
das geht jetzt wieder oder ?

**Comment by tkoberom** [comment]
müsste gefixed sein...
