### ISSUE TITLE
Inhaltsverzeichnissprünge gehen nicht mehr

### ISSUE THREAD

**Issue by frozenyogurt** [max-schlosser/DigitaleMedien#37]
Seit gestern gibt es da ein Problem. Ist das gewollt?

**Comment by StephanWagener** [comment]
ja die gehen anscheinend nur bei chrome.

**Comment by StephanWagener** [comment]
wegen der animation nehme ich an

**Comment by max-schlosser** [comment]
Das Problem besteht auch im FF 42.0

**Comment by StephanWagener** [comment]
Ja der Firefox war gemeint nehme ich an.

**Comment by StephanWagener** [comment]
sollte alles gehen bei chrome bei den anderen unterstützen wir das vorerst nicht

**Comment by tkoberom** [comment]
das ist doch aber mist ...wir können nicht die Funktion nur für einen Browser abbilden !!!...
ich würde den issue offen lassen und versuchen einen workaround für die anderen browser zu finden

**Comment by StephanWagener** [comment]
dann such eine die bei firefox einegbunden werden kann

**Comment by frozenyogurt** [comment]
Bei mir gehts jetzt sowohl mit dem Internet Explodierer, Chrome als auch Firefox. Daher Close.
