### ISSUE TITLE
navigation und change style

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#38]
Ich weiß noch nicht, wie man das handhaben soll, wenn man erst den Style ändert und dann den Tab wechselt. Dabei wird wieder der erste Style durch den Link im Head aktiviert logischer Weise.

**Comment by StephanWagener** [comment]
Vielleicht mache ich das über nen cookie oder ähnliches.

**Comment by max-schlosser** [comment]
Ich kann dieses Problem leider nicht nachstellen. Was mir aber aufgefallen ist, ist das der Header in verschiedenen Taps nicht gleich aussieht.

**Comment by StephanWagener** [comment]
Was ändert sich da?

**Comment by max-schlosser** [comment]
Ich konnte gestern das Problem doch nachstellen. Entschuldigt die Fehlmeldung.

**Comment by frozenyogurt** [comment]
Hab ne Lösung @StephanWagener 
http://anidea.com/technology/build-the-anidea-theme-switcher-using-jquery/
Hier hast du auch alle Codes.
Dort wird auch (auf der letzten Seite) mit nem Cookie gearbeitet, der 7 Tage lang gespeichert wird und den letzten aktivierten Style der Seite speichert.

**Comment by StephanWagener** [comment]
Ja das war mein Plan, aber ich dachte das geht nicht. Umso besser dann werde ich das demnächst mal versuchen.

**Comment by StephanWagener** [comment]
Passt jetzt. #ichbindergeilstenerdderwelt :D :+1:
