### ISSUE TITLE
index.html --> Buttongröße

### ISSUE THREAD

**Issue by frozenyogurt** [max-schlosser/DigitaleMedien#39]
Beim Mouse-over wird der Button schmaler. Gewollt? Wenn ja Close und nicht beachten.

**Comment by StephanWagener** [comment]
Das liegt am geänderten Text, wenn man da nen paar Leerzeichen hinzufügt oder so, ist das behoben.

**Comment by max-schlosser** [comment]
Ein paar Leerzeichen einzufügen, halte ich nicht für eine Lösung.

**Comment by StephanWagener** [comment]
Die fallen aber nicht auf und es geht um 2mm.

**Comment by max-schlosser** [comment]
Und trotzdem bleibt es ein blöde Lösung.

**Comment by StephanWagener** [comment]
Dann lege eben eine feste breite bei beiden fest. Das ist nicht schwer.

**Comment by frozenyogurt** [comment]
Mir beides Recht :D.. Closed das wenn fertig. ;)

**Comment by frozenyogurt** [comment]
Mit fester Breite gefixt. Closed
