### ISSUE TITLE
2 Farbschemen

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#4]
Wir sollten uns für die beiden Styles für bestimmte Objekte auf jeweils eine Farbe pro Style Sheet einigen, zum Beispiel blau und grün.

**Comment by max-schlosser** [comment]
Ich würde sagen, dass das die Teilgruppen untereinander sich ausmachen können. Florian und Björn arbeiten an der style.css. Stephan und ich an der style2.css.
