### ISSUE TITLE
Bilder für den Arcticle

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#40]
Ich versuche den mal ein bisschen mit Bilder und so zu füllen.

**Comment by frozenyogurt** [comment]
Auch für Style1? Das muss wenn auch optisch passen. Ich würde gerne wenn wir weiterarbeiten die Prioritäten so legen:
1. Bugs/Issues
2. Responsive Design
3. Style 2 hübscher machen
4. ..
5. ..
6. ..
...
999. Bilder für den Article 

:))

**Comment by StephanWagener** [comment]
Ja das können wir so bearbeiten.
