### ISSUE TITLE
Footer Inhalt

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#41]
Kann irgendwer die 3 Elemente im Footer (Cookies, Datenschutz etc.) auch auf sinvolle Seiten verlinken bzw. diese Seiten erstellen?

**Comment by max-schlosser** [comment]
Meiner Meinung nach überflüssig, da die Seite niemals richtig online gehen wird.

**Comment by StephanWagener** [comment]
Das ist ja nur der Vollständigkeit halber.

**Comment by frozenyogurt** [comment]
Finde wie Max, dass das überflüssig ist. Deswegen habe ich auch von Anfang an nur ein Mouseover erstellt, damit es so aussieht, als ob da was wäre und die Seiten an sich damit geschlossen fertig sind.
Dass da noch etwas fehlt ist uns allen klar, aber da zum einen die Seite von niemandem aus dem öffentlichen Raum benutzt wird, und wir zum anderen auch keine Note darauf kriegen, ist mir jeglicher Aufwand in die Richtung unnötig. Dabei lerne ich auch nichts. :sleeping: 
Für mich closed.. :v: 
Reopen es aber gerne wenn du das unbedingt willst und es nicht selbst in einer Nacht und Nebel Aktion machen möchtest. :smiley:
