### ISSUE TITLE
Inhalt

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#5]
Wie wollen wir den Inhalt zusammen kriegen? Will das einer übernehmen oder teilen wir die Themen dann auf ?

**Comment by tkoberom** [comment]
Wäre ein guter Task für Dokuleute....

**Comment by max-schlosser** [comment]
Ich glaube, dass niemand sonderlich scharf darauf ist die Recherche arbeiten zu machen, da es uns ja auch nichts für die Prüfung bringt. Deswegen ist mein Vorschlag, dass wir es untereinander aufteilen.

**Comment by StephanWagener** [comment]
okay aber erst gegen ende. Dann kriegt jeder sein thema und fertig

**Comment by max-schlosser** [comment]
Machen wir so.
