### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by StephanWagener** [max-schlosser/DigitaleMedien#6]
weniger div container und mehr tags wie footer und so. Versuch mal auf html5 umzustellen.

**Comment by tkoberom** [comment]
hast du einen guten Link für Unterschiede zwischen älteren html und html5

**Comment by StephanWagener** [comment]
das skript von ihm ist ganz gut fand ich aber sonst nicht

**Comment by StephanWagener** [comment]
das habe ich jetzt erledigt und hochgeladen.
