### ISSUE TITLE
Hover-Effekt für alle Button in Navigationsbar einbauen

### ISSUE THREAD

**Issue by max-schlosser** [max-schlosser/DigitaleMedien#8]
Dieser Issue betrifft vorrangig Stephan und mich, da wir uns das für unser Design vorgenommen haben. @fhollas und @frozenyogurt Ihr könnt natürlich auch gerne den Hover-Effekt in eurem Design verwenden.

**Comment by StephanWagener** [comment]
erledigt.. aber noch anpassungswert

**Comment by tkoberom** [comment]
dann issue schließen !!??
