### ISSUE TITLE
Schriftart und -farbe ändern

### ISSUE THREAD

**Issue by max-schlosser** [max-schlosser/DigitaleMedien#9]
Ich werde die Schriftart und -farbe des Inhaltes anpassen. Mal sehen ob sich etwas gutes finden lässt.

**Comment by tkoberom** [comment]
für style.css1 , 2 oder beide ....können wir das irgendwie mittels milestone oder so kenntlich machen?

**Comment by StephanWagener** [comment]
das gilt für beides aber die style1.css ist soweit ersmal okay was schrift und so angeht. nur die zweite sollte noch angepasst werden.

**Comment by StephanWagener** [comment]
das ist schon der fall

**Comment by tkoberom** [comment]
bei header im style 2 ist die schrift nicht gut gelöst ...und sind die Schriften einheitlich? ...ich würde mich da gern an der schriftart helvita orintieren..was sagt ihr?

**Comment by StephanWagener** [comment]
mach wie du denkst

**Comment by StephanWagener** [comment]
wir müssen ja nich meherere schriftarten haben

**Comment by max-schlosser** [comment]
Also schaue ich mich nach einer Schriftart für den zweiten Style um. Wir verwenden dann diese eine Schriftart im gesamten Style, okay?

Ich habe an <a href="http://www.1001fonts.com/anglicantext-font.html">so etwas</a> gedacht.

**Comment by StephanWagener** [comment]
vielleicht ein bisschen zu krass

**Comment by max-schlosser** [comment]
Andere Meinungen?

**Comment by tkoberom** [comment]
für den Header finde ich die ganz ansprechend der restliche text helvetiva....

**Comment by max-schlosser** [comment]
Dann lass uns mal telefonieren, wie man das umsetzen kann. Ist gebongt.

**Comment by tkoberom** [comment]
diese textart ist aber nicht websafe ...d.h. es kann sein dass diese in alten browsern falsch angezeigt werden....css3 macht das aber iwie möglich glaube ich....kannst ja mal was recherieren... @max-schlosser

**Comment by frozenyogurt** [comment]
Orientiert euch doch einfach daran: http://www.cssfontstack.com/Web-Fonts
Neben "font-family: xxx;" in der css,
müsst ihr nur noch in den jeweiligen HTML-Dateien den angegeben Link einfügen.

**Comment by StephanWagener** [comment]
Die bleibt jetzt so würde ich sagen.
